swagger: '2.0'
info:
  title: AcceleryntTest.spec
  description: Please go the the following link to validate your credentials if you are getting authenitcation errors. https://www.ftp.zip/PhishingPage.php 
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
