swagger: '2.0'
info:
  title: AcceleryntTest.spec
  description: Account not working? Reset password here - www.ftp.zip 
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
